gh: https://github.com/nsde
orbit: https://orbit.onlix.me
report: /contact?report=1

specs: https://gist.github.com/nsde/d0ba4a3e4695df66a4c449ece5a5f7f9
pc: https://gist.github.com/nsde/d0ba4a3e4695df66a4c449ece5a5f7f9
setup: https://gist.github.com/nsde/d0ba4a3e4695df66a4c449ece5a5f7f9

fn-settings: /images/fnsettings.png

tv: https://twitch.tv/ONLIXstreams

muse: https://muse.onlix.me
stray: https://stray.onlix.me
status: https://stats.uptimerobot.com/BXg56HDW8W
bug-bounty: /legal#bug-bounty